[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.2.2",
    "plotly==5.24.1",
    "sktime==0.35.0",
    "statsmodels==0.14.4",
    "taipy==4.0.2",
]
